/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductBacklogResponse } from '../../models/product-backlog-response';

export interface FindProductBacklogByProjectId$Params {
  'project-id': number;
}

export function findProductBacklogByProjectId(http: HttpClient, rootUrl: string, params: FindProductBacklogByProjectId$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductBacklogResponse>> {
  const rb = new RequestBuilder(rootUrl, findProductBacklogByProjectId.PATH, 'get');
  if (params) {
    rb.path('project-id', params['project-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductBacklogResponse>;
    })
  );
}

findProductBacklogByProjectId.PATH = '/product-backlogs/project/{project-id}';
