/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjetRequest } from '../../models/projet-request';
import { ProjetResponse } from '../../models/projet-response';

export interface UpdateProjet$Params {
  projet_id: number;
      body: ProjetRequest
}

export function updateProjet(http: HttpClient, rootUrl: string, params: UpdateProjet$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjetResponse>> {
  const rb = new RequestBuilder(rootUrl, updateProjet.PATH, 'put');
  if (params) {
    rb.path('projet_id', params.projet_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjetResponse>;
    })
  );
}

updateProjet.PATH = '/projets/update/{projet_id}';
