/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserStoryResponse } from '../../models/user-story-response';

export interface FindUserStoriesBySprintBacklog$Params {
  'sprint-backlog-id': number;
}

export function findUserStoriesBySprintBacklog(http: HttpClient, rootUrl: string, params: FindUserStoriesBySprintBacklog$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserStoryResponse>>> {
  const rb = new RequestBuilder(rootUrl, findUserStoriesBySprintBacklog.PATH, 'get');
  if (params) {
    rb.path('sprint-backlog-id', params['sprint-backlog-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserStoryResponse>>;
    })
  );
}

findUserStoriesBySprintBacklog.PATH = '/user-stories/sprint-backlog/{sprint-backlog-id}';
