/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserStoryResponse } from '../../models/user-story-response';

export interface FindUserStoriesByStatut$Params {
  statut: 'A_FAIRE' | 'EN_COURS' | 'TERMINE';
}

export function findUserStoriesByStatut(http: HttpClient, rootUrl: string, params: FindUserStoriesByStatut$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserStoryResponse>>> {
  const rb = new RequestBuilder(rootUrl, findUserStoriesByStatut.PATH, 'get');
  if (params) {
    rb.path('statut', params.statut, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserStoryResponse>>;
    })
  );
}

findUserStoriesByStatut.PATH = '/user-stories/statut/{statut}';
