/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserStoryResponse } from '../../models/user-story-response';

export interface FindUserStoryById$Params {
  'user-story-id': number;
}

export function findUserStoryById(http: HttpClient, rootUrl: string, params: FindUserStoryById$Params, context?: HttpContext): Observable<StrictHttpResponse<UserStoryResponse>> {
  const rb = new RequestBuilder(rootUrl, findUserStoryById.PATH, 'get');
  if (params) {
    rb.path('user-story-id', params['user-story-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserStoryResponse>;
    })
  );
}

findUserStoryById.PATH = '/user-stories/{user-story-id}';
