/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseUserStoryResponse } from '../../models/page-response-user-story-response';

export interface SearchUserStories$Params {

/**
 * Titre de la User Story
 */
  titre?: string;

/**
 * Statut de la User Story
 */
  statut?: 'A_FAIRE' | 'EN_COURS' | 'TERMINE';

/**
 * Priorité de la User Story
 */
  priorite?: number;

/**
 * ID du Sprint Backlog
 */
  sprintBacklogId?: number;
  page?: number;
  size?: number;
}

export function searchUserStories(http: HttpClient, rootUrl: string, params?: SearchUserStories$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseUserStoryResponse>> {
  const rb = new RequestBuilder(rootUrl, searchUserStories.PATH, 'get');
  if (params) {
    rb.query('titre', params.titre, {});
    rb.query('statut', params.statut, {});
    rb.query('priorite', params.priorite, {});
    rb.query('sprintBacklogId', params.sprintBacklogId, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseUserStoryResponse>;
    })
  );
}

searchUserStories.PATH = '/user-stories/search';
