/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UpdateUserStoryStatut$Params {
  'user-story-id': number;
  statut: 'A_FAIRE' | 'EN_COURS' | 'TERMINE';
}

export function updateUserStoryStatut(http: HttpClient, rootUrl: string, params: UpdateUserStoryStatut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, updateUserStoryStatut.PATH, 'patch');
  if (params) {
    rb.path('user-story-id', params['user-story-id'], {});
    rb.query('statut', params.statut, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

updateUserStoryStatut.PATH = '/user-stories/{user-story-id}/statut';
