/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TacheResponse } from '../../models/tache-response';

export interface FindTacheById$Params {
  'tache-id': number;
}

export function findTacheById(http: HttpClient, rootUrl: string, params: FindTacheById$Params, context?: HttpContext): Observable<StrictHttpResponse<TacheResponse>> {
  const rb = new RequestBuilder(rootUrl, findTacheById.PATH, 'get');
  if (params) {
    rb.path('tache-id', params['tache-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TacheResponse>;
    })
  );
}

findTacheById.PATH = '/taches/{tache-id}';
