/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseTacheResponse } from '../../models/page-response-tache-response';

export interface FindTachesWithFilters$Params {
  titre?: string;
  statut?: 'A_FAIRE' | 'EN_COURS' | 'TERMINE';
  userId?: number;
  userStoryId?: number;
  page?: number;
  size?: number;
}

export function findTachesWithFilters(http: HttpClient, rootUrl: string, params?: FindTachesWithFilters$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseTacheResponse>> {
  const rb = new RequestBuilder(rootUrl, findTachesWithFilters.PATH, 'get');
  if (params) {
    rb.query('titre', params.titre, {});
    rb.query('statut', params.statut, {});
    rb.query('userId', params.userId, {});
    rb.query('userStoryId', params.userStoryId, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseTacheResponse>;
    })
  );
}

findTachesWithFilters.PATH = '/taches/search';
