/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BacklogItemResponse {
  completed?: boolean;
  description?: string;
  id?: number;
  inProgress?: boolean;
  points?: number;
  priorite?: number;
  productBacklogId?: number;
  productBacklogTitre?: string;
  projetNom?: string;
  statut?: 'EN_COURS' | 'TERMINE' | 'A_FAIRE';
  statutLabel?: string;
  titre?: string;
}
