/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductBacklog } from '../models/product-backlog';
export interface BacklogItem {
  description?: string;
  id?: number;
  points?: number;
  priorite?: number;
  productBacklog?: ProductBacklog;
  statut?: 'EN_COURS' | 'TERMINE' | 'A_FAIRE';
  titre?: string;
}
