/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BlocageRequest {
  commentaires?: Array<string>;
  dateResolution?: string;
  dateSignalement?: string;
  description: string;
  priorite: number;
  statut: 'EN_COURS' | 'EN_ATTENTE' | 'RESOLU';
  tacheId?: number;
  titre: string;
}
