/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BlocageResponse {
  commentaires?: Array<string>;
  dateResolution?: string;
  dateSignalement?: string;
  description?: string;
  id?: number;
  priorite?: number;
  resolu?: boolean;
  statut?: 'EN_COURS' | 'EN_ATTENTE' | 'RESOLU';
  tacheId?: number;
  tacheTitre?: string;
  titre?: string;
}
