/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Tache } from '../models/tache';
export interface Blocage {
  commentaires?: Array<string>;
  dateResolution?: string;
  dateSignalement?: string;
  description?: string;
  id?: number;
  priorite?: number;
  statut?: 'EN_COURS' | 'EN_ATTENTE' | 'RESOLU';
  tache?: Tache;
  titre?: string;
}
