/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Projet } from '../models/projet';
import { User } from '../models/user';
export interface Meeting {
  date?: string;
  debut?: string;
  description?: string;
  fin?: string;
  id?: number;
  meetingPassword?: string;
  meetingUrl?: string;
  participants?: Array<User>;
  projet?: Projet;
  titre?: string;
  type?: 'DAILY' | 'PLANNING' | 'REVIEW' | 'RETROSPECTIVE';
}
