/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ParticipantResponse } from '../models/participant-response';
export interface MeetingResponse {
  date?: string;
  debut?: string;
  description?: string;
  dureeMinutes?: number;
  fin?: string;
  id?: number;
  meetingPassword?: string;
  meetingUrl?: string;
  nombreParticipants?: number;
  ongoing?: boolean;
  participants?: Array<ParticipantResponse>;
  past?: boolean;
  projetId?: number;
  projetNom?: string;
  titre?: string;
  type?: 'DAILY' | 'PLANNING' | 'REVIEW' | 'RETROSPECTIVE';
  upcoming?: boolean;
}
