/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MeetingRequest {
  date: string;
  debut: string;
  description?: string;
  fin: string;
  meetingPassword?: string;
  meetingUrl?: string;
  participantIds?: Array<number>;
  projetId: number;
  titre: string;
  type: 'DAILY' | 'PLANNING' | 'REVIEW' | 'RETROSPECTIVE';
}
