/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationResponse {
  createdDate?: string;
  dateEnvoi?: string;
  id?: number;
  isRead?: boolean;
  lastModifiedDate?: string;
  message?: string;
  title?: string;
  type?: 'INFO' | 'SUCCESS' | 'WARNING' | 'ERROR' | 'REMINDER';
  userFullName?: string;
  userId?: number;
}
