/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Notification {
  dateDebut?: string;
  dateEnvoi?: string;
  id?: number;
  isRead?: boolean;
  message?: string;
  title?: string;
  type?: 'INFO' | 'SUCCESS' | 'WARNING' | 'ERROR' | 'REMINDER';
  user?: User;
}
