/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SprintBacklogResponse } from '../models/sprint-backlog-response';
export interface PageResponseSprintBacklogResponse {
  content?: Array<SprintBacklogResponse>;
  first?: boolean;
  last?: boolean;
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
