/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BacklogItemResponse } from '../models/backlog-item-response';
export interface PageResponseBacklogItemResponse {
  content?: Array<BacklogItemResponse>;
  first?: boolean;
  last?: boolean;
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
