/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductBacklogResponse } from '../models/product-backlog-response';
export interface PageResponseProductBacklogResponse {
  content?: Array<ProductBacklogResponse>;
  first?: boolean;
  last?: boolean;
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
