/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductBacklogResponse {
  backlogItemsCount?: number;
  id?: number;
  productOwnerName?: string;
  projectId?: number;
  projectName?: string;
}
