/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BacklogItem } from '../models/backlog-item';
import { Projet } from '../models/projet';
export interface ProductBacklog {
  id?: number;
  items?: Array<BacklogItem>;
  projet?: Projet;
}
