/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Meeting } from '../models/meeting';
import { ProductBacklog } from '../models/product-backlog';
import { Sprint } from '../models/sprint';
import { User } from '../models/user';
export interface Projet {
  actif?: boolean;
  dateDebut?: string;
  dateFin?: string;
  description: string;
  id?: number;
  meetings?: Array<Meeting>;
  nom: string;
  productBacklog?: ProductBacklog;
  productOwner?: User;
  scrumMaster?: User;
  sprints?: Array<Sprint>;
  statut?: 'EN_COURS' | 'TERMINE' | 'EN_PAUSE' | 'A_FAIRE';
  users?: Array<User>;
}
