/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface ProjetRequest {
  actif?: boolean;
  dateDebut: string;
  description: string;
  id?: number;
  nom: string;
  productOwner: User;
  scrumMaster: User;
}
