/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Sprint } from '../models/sprint';
import { UserStory } from '../models/user-story';
export interface SprintBacklog {
  id?: number;
  sprint?: Sprint;
  userStories?: Array<UserStory>;
}
