/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserStoryResponse } from '../models/user-story-response';
export interface SprintBacklogResponse {
  completedStoryPoints?: number;
  completedUserStories?: number;
  completionPercentage?: number;
  id?: number;
  sprintDateDebut?: string;
  sprintDateFin?: string;
  sprintId?: number;
  sprintNom?: string;
  sprintStatut?: string;
  storyPointsCompletionPercentage?: number;
  totalStoryPoints?: number;
  totalUserStories?: number;
  userStories?: Array<UserStoryResponse>;
}
