/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SprintRequest {
  dateDebut: string;
  dateFin: string;
  nom: string;
  objectif?: string;
  projetId: number;
}
