/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Projet } from '../models/projet';
import { SprintBacklog } from '../models/sprint-backlog';
export interface Sprint {
  dateDebut?: string;
  dateFin?: string;
  id?: number;
  nom?: string;
  objectif?: string;
  projet?: Projet;
  sprintBacklog?: SprintBacklog;
  statut?: 'A_FAIRE' | 'EN_COURS' | 'TERMINE';
}
