/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SprintResponse {
  completedStoryPoints?: number;
  completedUserStories?: number;
  completionPercentage?: number;
  dateDebut?: string;
  dateFin?: string;
  daysRemaining?: number;
  durationInDays?: number;
  id?: number;
  isActive?: boolean;
  isOverdue?: boolean;
  nom?: string;
  objectif?: string;
  projetId?: number;
  projetNom?: string;
  sprintBacklogId?: number;
  statut?: 'A_FAIRE' | 'EN_COURS' | 'TERMINE';
  storyPointsCompletionPercentage?: number;
  totalStoryPoints?: number;
  totalUserStories?: number;
}
