/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Blocage } from '../models/blocage';
import { User } from '../models/user';
import { UserStory } from '../models/user-story';
export interface Tache {
  blocage?: Blocage;
  description?: string;
  estimation?: number;
  id?: number;
  statut?: 'A_FAIRE' | 'EN_COURS' | 'TERMINE';
  titre?: string;
  user?: User;
  userStory?: UserStory;
}
