/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TacheRequest {
  assigneAId?: number;
  description?: string;
  estimation?: number;
  statut?: 'A_FAIRE' | 'EN_COURS' | 'TERMINE';
  titre: string;
  userStoryId: number;
}
