/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlocageInfo } from '../models/blocage-info';
export interface TacheResponse {
  assigneAId?: number;
  assigneANom?: string;
  blocage?: BlocageInfo;
  description?: string;
  estimation?: number;
  id?: number;
  statut?: 'A_FAIRE' | 'EN_COURS' | 'TERMINE';
  titre?: string;
  userStoryId?: number;
  userStoryTitre?: string;
}
