/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SprintBacklog } from '../models/sprint-backlog';
import { Tache } from '../models/tache';
export interface UserStory {
  description?: string;
  id?: number;
  points?: number;
  priorite?: number;
  sprintBacklog?: SprintBacklog;
  statut?: 'A_FAIRE' | 'EN_COURS' | 'TERMINE';
  taches?: Array<Tache>;
  titre?: string;
}
