/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TacheResponse } from '../models/tache-response';
export interface UserStoryResponse {
  description?: string;
  id?: number;
  nombreTaches?: number;
  nombreTachesTerminees?: number;
  points?: number;
  pourcentageCompletion?: number;
  priorite?: number;
  sprintBacklogId?: number;
  sprintBacklogNom?: string;
  statut?: 'A_FAIRE' | 'EN_COURS' | 'TERMINE';
  taches?: Array<TacheResponse>;
  titre?: string;
}
