/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserStoryRequest {
  description?: string;
  points?: number;
  priorite: number;
  sprintBacklogId?: number;
  statut?: 'A_FAIRE' | 'EN_COURS' | 'TERMINE';
  titre: string;
}
