/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrantedAuthority } from '../models/granted-authority';
import { Notification } from '../models/notification';
import { Role } from '../models/role';
import { Tache } from '../models/tache';
export interface User {
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  accountlocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  dateNaissance?: string;
  email?: string;
  enabled?: boolean;
  fullName?: string;
  id?: number;
  lastModifiedDate?: string;
  name?: string;
  nom?: string;
  notifications?: Array<Notification>;
  password?: string;
  prenom?: string;
  roles?: Array<Role>;
  taches?: Array<Tache>;
  username?: string;
}
