/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SprintResponse } from '../../models/sprint-response';

export interface ChangeSprintStatut$Params {
  'sprint-id': number;
  statut: 'A_FAIRE' | 'EN_COURS' | 'TERMINE';
}

export function changeSprintStatut(http: HttpClient, rootUrl: string, params: ChangeSprintStatut$Params, context?: HttpContext): Observable<StrictHttpResponse<SprintResponse>> {
  const rb = new RequestBuilder(rootUrl, changeSprintStatut.PATH, 'patch');
  if (params) {
    rb.path('sprint-id', params['sprint-id'], {});
    rb.query('statut', params.statut, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SprintResponse>;
    })
  );
}

changeSprintStatut.PATH = '/sprints/{sprint-id}/statut';
