/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SprintResponse } from '../../models/sprint-response';

export interface FindActiveSprintsOnDate$Params {

/**
 * Date au format YYYY-MM-DD
 */
  date: string;
}

export function findActiveSprintsOnDate(http: HttpClient, rootUrl: string, params: FindActiveSprintsOnDate$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SprintResponse>>> {
  const rb = new RequestBuilder(rootUrl, findActiveSprintsOnDate.PATH, 'get');
  if (params) {
    rb.path('date', params.date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SprintResponse>>;
    })
  );
}

findActiveSprintsOnDate.PATH = '/sprints/active/{date}';
