/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SprintResponse } from '../../models/sprint-response';

export interface FindSprintById$Params {
  'sprint-id': number;
}

export function findSprintById(http: HttpClient, rootUrl: string, params: FindSprintById$Params, context?: HttpContext): Observable<StrictHttpResponse<SprintResponse>> {
  const rb = new RequestBuilder(rootUrl, findSprintById.PATH, 'get');
  if (params) {
    rb.path('sprint-id', params['sprint-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SprintResponse>;
    })
  );
}

findSprintById.PATH = '/sprints/{sprint-id}';
