/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseSprintResponse } from '../../models/page-response-sprint-response';

export interface SearchSprints$Params {
  nom?: string;
  statut?: 'A_FAIRE' | 'EN_COURS' | 'TERMINE';
  page?: number;
  size?: number;
}

export function searchSprints(http: HttpClient, rootUrl: string, params?: SearchSprints$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseSprintResponse>> {
  const rb = new RequestBuilder(rootUrl, searchSprints.PATH, 'get');
  if (params) {
    rb.query('nom', params.nom, {});
    rb.query('statut', params.statut, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseSprintResponse>;
    })
  );
}

searchSprints.PATH = '/sprints/search';
