/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SprintRequest } from '../../models/sprint-request';
import { SprintResponse } from '../../models/sprint-response';

export interface UpdateSprint$Params {
  'sprint-id': number;
      body: SprintRequest
}

export function updateSprint(http: HttpClient, rootUrl: string, params: UpdateSprint$Params, context?: HttpContext): Observable<StrictHttpResponse<SprintResponse>> {
  const rb = new RequestBuilder(rootUrl, updateSprint.PATH, 'put');
  if (params) {
    rb.path('sprint-id', params['sprint-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SprintResponse>;
    })
  );
}

updateSprint.PATH = '/sprints/{sprint-id}';
