/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseNotificationResponse } from '../../models/page-response-notification-response';

export interface FindNotificationsByType$Params {
  type: 'INFO' | 'SUCCESS' | 'WARNING' | 'ERROR' | 'REMINDER';
  page?: number;
  size?: number;
}

export function findNotificationsByType(http: HttpClient, rootUrl: string, params: FindNotificationsByType$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseNotificationResponse>> {
  const rb = new RequestBuilder(rootUrl, findNotificationsByType.PATH, 'get');
  if (params) {
    rb.path('type', params.type, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseNotificationResponse>;
    })
  );
}

findNotificationsByType.PATH = '/notifications/type/{type}';
