/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseNotificationResponse } from '../../models/page-response-notification-response';

export interface SearchNotifications$Params {
  isRead?: boolean;
  type?: 'INFO' | 'SUCCESS' | 'WARNING' | 'ERROR' | 'REMINDER';
  startDate?: string;
  endDate?: string;
  page?: number;
  size?: number;
}

export function searchNotifications(http: HttpClient, rootUrl: string, params?: SearchNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseNotificationResponse>> {
  const rb = new RequestBuilder(rootUrl, searchNotifications.PATH, 'get');
  if (params) {
    rb.query('isRead', params.isRead, {});
    rb.query('type', params.type, {});
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseNotificationResponse>;
    })
  );
}

searchNotifications.PATH = '/notifications/search';
