/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AddUserStoriesToBacklog$Params {

/**
 * Sprint Backlog ID
 */
  'sprint-backlog-id': number;
      body: Array<number>
}

export function addUserStoriesToBacklog(http: HttpClient, rootUrl: string, params: AddUserStoriesToBacklog$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, addUserStoriesToBacklog.PATH, 'post');
  if (params) {
    rb.path('sprint-backlog-id', params['sprint-backlog-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

addUserStoriesToBacklog.PATH = '/sprint-backlogs/{sprint-backlog-id}/user-stories';
