/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SprintBacklogResponse } from '../../models/sprint-backlog-response';

export interface GetSprintBacklogById$Params {

/**
 * Sprint Backlog ID
 */
  'sprint-backlog-id': number;
}

export function getSprintBacklogById(http: HttpClient, rootUrl: string, params: GetSprintBacklogById$Params, context?: HttpContext): Observable<StrictHttpResponse<SprintBacklogResponse>> {
  const rb = new RequestBuilder(rootUrl, getSprintBacklogById.PATH, 'get');
  if (params) {
    rb.path('sprint-backlog-id', params['sprint-backlog-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SprintBacklogResponse>;
    })
  );
}

getSprintBacklogById.PATH = '/sprint-backlogs/{sprint-backlog-id}';
