/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseSprintBacklogResponse } from '../../models/page-response-sprint-backlog-response';

export interface GetAllSprintBacklogs$Params {

/**
 * Page number (0-based)
 */
  page?: number;

/**
 * Page size
 */
  size?: number;
}

export function getAllSprintBacklogs(http: HttpClient, rootUrl: string, params?: GetAllSprintBacklogs$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseSprintBacklogResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllSprintBacklogs.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseSprintBacklogResponse>;
    })
  );
}

getAllSprintBacklogs.PATH = '/sprint-backlogs';
