/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RemoveUserStoryFromBacklog$Params {

/**
 * Sprint Backlog ID
 */
  'sprint-backlog-id': number;

/**
 * User Story ID
 */
  'user-story-id': number;
}

export function removeUserStoryFromBacklog(http: HttpClient, rootUrl: string, params: RemoveUserStoryFromBacklog$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, removeUserStoryFromBacklog.PATH, 'delete');
  if (params) {
    rb.path('sprint-backlog-id', params['sprint-backlog-id'], {});
    rb.path('user-story-id', params['user-story-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

removeUserStoryFromBacklog.PATH = '/sprint-backlogs/{sprint-backlog-id}/user-stories/{user-story-id}';
