/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BacklogItemResponse } from '../../models/backlog-item-response';

export interface FindByPriorityOrder$Params {
  'product-backlog-id': number;
  ascending?: boolean;
}

export function findByPriorityOrder(http: HttpClient, rootUrl: string, params: FindByPriorityOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BacklogItemResponse>>> {
  const rb = new RequestBuilder(rootUrl, findByPriorityOrder.PATH, 'get');
  if (params) {
    rb.query('product-backlog-id', params['product-backlog-id'], {});
    rb.query('ascending', params.ascending, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BacklogItemResponse>>;
    })
  );
}

findByPriorityOrder.PATH = '/backlog-items/priorite';
