/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseBacklogItemResponse } from '../../models/page-response-backlog-item-response';

export interface FindByStatut$Params {
  statut: 'EN_COURS' | 'TERMINE' | 'A_FAIRE';
  page?: number;
  size?: number;
}

export function findByStatut(http: HttpClient, rootUrl: string, params: FindByStatut$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBacklogItemResponse>> {
  const rb = new RequestBuilder(rootUrl, findByStatut.PATH, 'get');
  if (params) {
    rb.path('statut', params.statut, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseBacklogItemResponse>;
    })
  );
}

findByStatut.PATH = '/backlog-items/statut/{statut}';
