/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BacklogItemResponse } from '../../models/backlog-item-response';

export interface FindBacklogItemById$Params {
  'backlog-item-id': number;
}

export function findBacklogItemById(http: HttpClient, rootUrl: string, params: FindBacklogItemById$Params, context?: HttpContext): Observable<StrictHttpResponse<BacklogItemResponse>> {
  const rb = new RequestBuilder(rootUrl, findBacklogItemById.PATH, 'get');
  if (params) {
    rb.path('backlog-item-id', params['backlog-item-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BacklogItemResponse>;
    })
  );
}

findBacklogItemById.PATH = '/backlog-items/{backlog-item-id}';
