/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseBacklogItemResponse } from '../../models/page-response-backlog-item-response';

export interface FindWithFilters$Params {
  titre?: string;
  statut?: 'EN_COURS' | 'TERMINE' | 'A_FAIRE';
  'product-backlog-id'?: number;
  'min-priorite'?: number;
  'max-priorite'?: number;
  page?: number;
  size?: number;
}

export function findWithFilters(http: HttpClient, rootUrl: string, params?: FindWithFilters$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBacklogItemResponse>> {
  const rb = new RequestBuilder(rootUrl, findWithFilters.PATH, 'get');
  if (params) {
    rb.query('titre', params.titre, {});
    rb.query('statut', params.statut, {});
    rb.query('product-backlog-id', params['product-backlog-id'], {});
    rb.query('min-priorite', params['min-priorite'], {});
    rb.query('max-priorite', params['max-priorite'], {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseBacklogItemResponse>;
    })
  );
}

findWithFilters.PATH = '/backlog-items/filter';
