/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BacklogItemResponse } from '../../models/backlog-item-response';

export interface UpdatePriorite$Params {
  'backlog-item-id': number;
  priorite: number;
}

export function updatePriorite(http: HttpClient, rootUrl: string, params: UpdatePriorite$Params, context?: HttpContext): Observable<StrictHttpResponse<BacklogItemResponse>> {
  const rb = new RequestBuilder(rootUrl, updatePriorite.PATH, 'patch');
  if (params) {
    rb.path('backlog-item-id', params['backlog-item-id'], {});
    rb.query('priorite', params.priorite, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BacklogItemResponse>;
    })
  );
}

updatePriorite.PATH = '/backlog-items/{backlog-item-id}/priorite';
