/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BacklogItemRequest } from '../../models/backlog-item-request';
import { BacklogItemResponse } from '../../models/backlog-item-response';

export interface UpdateBacklogItem$Params {
  'backlog-item-id': number;
      body: BacklogItemRequest
}

export function updateBacklogItem(http: HttpClient, rootUrl: string, params: UpdateBacklogItem$Params, context?: HttpContext): Observable<StrictHttpResponse<BacklogItemResponse>> {
  const rb = new RequestBuilder(rootUrl, updateBacklogItem.PATH, 'put');
  if (params) {
    rb.path('backlog-item-id', params['backlog-item-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BacklogItemResponse>;
    })
  );
}

updateBacklogItem.PATH = '/backlog-items/{backlog-item-id}';
