/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { UserStoryService } from './services/user-story.service';
import { TacheService } from './services/tache.service';
import { SprintService } from './services/sprint.service';
import { ProjetService } from './services/projet.service';
import { ProductBacklogService } from './services/product-backlog.service';
import { NotificationService } from './services/notification.service';
import { MeetingService } from './services/meeting.service';
import { BlocageService } from './services/blocage.service';
import { BacklogItemService } from './services/backlog-item.service';
import { SprintBacklogService } from './services/sprint-backlog.service';
import { AuthenticationService } from './services/authentication.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    UserStoryService,
    TacheService,
    SprintService,
    ProjetService,
    ProductBacklogService,
    NotificationService,
    MeetingService,
    BlocageService,
    BacklogItemService,
    SprintBacklogService,
    AuthenticationService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
