/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MeetingResponse } from '../../models/meeting-response';

export interface FindUpcomingMeetings$Params {
}

export function findUpcomingMeetings(http: HttpClient, rootUrl: string, params?: FindUpcomingMeetings$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MeetingResponse>>> {
  const rb = new RequestBuilder(rootUrl, findUpcomingMeetings.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MeetingResponse>>;
    })
  );
}

findUpcomingMeetings.PATH = '/meetings/upcoming';
