/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseMeetingResponse } from '../../models/page-response-meeting-response';

export interface FindMeetingsByProject$Params {
  'project-id': number;
  page?: number;
  size?: number;
}

export function findMeetingsByProject(http: HttpClient, rootUrl: string, params: FindMeetingsByProject$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseMeetingResponse>> {
  const rb = new RequestBuilder(rootUrl, findMeetingsByProject.PATH, 'get');
  if (params) {
    rb.path('project-id', params['project-id'], {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseMeetingResponse>;
    })
  );
}

findMeetingsByProject.PATH = '/meetings/project/{project-id}';
