/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MeetingResponse } from '../../models/meeting-response';

export interface FindMeetingById$Params {
  'meeting-id': number;
}

export function findMeetingById(http: HttpClient, rootUrl: string, params: FindMeetingById$Params, context?: HttpContext): Observable<StrictHttpResponse<MeetingResponse>> {
  const rb = new RequestBuilder(rootUrl, findMeetingById.PATH, 'get');
  if (params) {
    rb.path('meeting-id', params['meeting-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MeetingResponse>;
    })
  );
}

findMeetingById.PATH = '/meetings/{meeting-id}';
