/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseMeetingResponse } from '../../models/page-response-meeting-response';

export interface FindMeetingsByType$Params {
  type: 'DAILY' | 'PLANNING' | 'REVIEW' | 'RETROSPECTIVE';
  page?: number;
  size?: number;
}

export function findMeetingsByType(http: HttpClient, rootUrl: string, params: FindMeetingsByType$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseMeetingResponse>> {
  const rb = new RequestBuilder(rootUrl, findMeetingsByType.PATH, 'get');
  if (params) {
    rb.path('type', params.type, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseMeetingResponse>;
    })
  );
}

findMeetingsByType.PATH = '/meetings/type/{type}';
