/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BlocageResponse } from '../../models/blocage-response';

export interface ChangeStatut$Params {
  'blocage-id': number;
  statut: 'EN_COURS' | 'EN_ATTENTE' | 'RESOLU';
}

export function changeStatut(http: HttpClient, rootUrl: string, params: ChangeStatut$Params, context?: HttpContext): Observable<StrictHttpResponse<BlocageResponse>> {
  const rb = new RequestBuilder(rootUrl, changeStatut.PATH, 'patch');
  if (params) {
    rb.path('blocage-id', params['blocage-id'], {});
    rb.query('statut', params.statut, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BlocageResponse>;
    })
  );
}

changeStatut.PATH = '/blocages/{blocage-id}/statut';
