/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseBlocageResponse } from '../../models/page-response-blocage-response';

export interface GetBlocagesByStatut$Params {
  statut: 'EN_COURS' | 'EN_ATTENTE' | 'RESOLU';
  page?: number;
  size?: number;
}

export function getBlocagesByStatut(http: HttpClient, rootUrl: string, params: GetBlocagesByStatut$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBlocageResponse>> {
  const rb = new RequestBuilder(rootUrl, getBlocagesByStatut.PATH, 'get');
  if (params) {
    rb.path('statut', params.statut, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseBlocageResponse>;
    })
  );
}

getBlocagesByStatut.PATH = '/blocages/statut/{statut}';
