/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BlocageRequest } from '../../models/blocage-request';
import { BlocageResponse } from '../../models/blocage-response';

export interface UpdateBlocage$Params {
  'blocage-id': number;
      body: BlocageRequest
}

export function updateBlocage(http: HttpClient, rootUrl: string, params: UpdateBlocage$Params, context?: HttpContext): Observable<StrictHttpResponse<BlocageResponse>> {
  const rb = new RequestBuilder(rootUrl, updateBlocage.PATH, 'put');
  if (params) {
    rb.path('blocage-id', params['blocage-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BlocageResponse>;
    })
  );
}

updateBlocage.PATH = '/blocages/{blocage-id}';
