/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BacklogItemResponse } from '../models/backlog-item-response';
import { changeStatut1 } from '../fn/backlog-item/change-statut-1';
import { ChangeStatut1$Params } from '../fn/backlog-item/change-statut-1';
import { createBacklogItem } from '../fn/backlog-item/create-backlog-item';
import { CreateBacklogItem$Params } from '../fn/backlog-item/create-backlog-item';
import { deleteBacklogItem } from '../fn/backlog-item/delete-backlog-item';
import { DeleteBacklogItem$Params } from '../fn/backlog-item/delete-backlog-item';
import { findAllBacklogItems } from '../fn/backlog-item/find-all-backlog-items';
import { FindAllBacklogItems$Params } from '../fn/backlog-item/find-all-backlog-items';
import { findBacklogItemById } from '../fn/backlog-item/find-backlog-item-by-id';
import { FindBacklogItemById$Params } from '../fn/backlog-item/find-backlog-item-by-id';
import { findByPriorityOrder } from '../fn/backlog-item/find-by-priority-order';
import { FindByPriorityOrder$Params } from '../fn/backlog-item/find-by-priority-order';
import { findByProductBacklog } from '../fn/backlog-item/find-by-product-backlog';
import { FindByProductBacklog$Params } from '../fn/backlog-item/find-by-product-backlog';
import { findByStatut } from '../fn/backlog-item/find-by-statut';
import { FindByStatut$Params } from '../fn/backlog-item/find-by-statut';
import { findWithFilters } from '../fn/backlog-item/find-with-filters';
import { FindWithFilters$Params } from '../fn/backlog-item/find-with-filters';
import { PageResponseBacklogItemResponse } from '../models/page-response-backlog-item-response';
import { searchBacklogItems } from '../fn/backlog-item/search-backlog-items';
import { SearchBacklogItems$Params } from '../fn/backlog-item/search-backlog-items';
import { updateBacklogItem } from '../fn/backlog-item/update-backlog-item';
import { UpdateBacklogItem$Params } from '../fn/backlog-item/update-backlog-item';
import { updatePriorite } from '../fn/backlog-item/update-priorite';
import { UpdatePriorite$Params } from '../fn/backlog-item/update-priorite';

@Injectable({ providedIn: 'root' })
export class BacklogItemService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findBacklogItemById()` */
  static readonly FindBacklogItemByIdPath = '/backlog-items/{backlog-item-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findBacklogItemById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findBacklogItemById$Response(params: FindBacklogItemById$Params, context?: HttpContext): Observable<StrictHttpResponse<BacklogItemResponse>> {
    return findBacklogItemById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findBacklogItemById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findBacklogItemById(params: FindBacklogItemById$Params, context?: HttpContext): Observable<BacklogItemResponse> {
    return this.findBacklogItemById$Response(params, context).pipe(
      map((r: StrictHttpResponse<BacklogItemResponse>): BacklogItemResponse => r.body)
    );
  }

  /** Path part for operation `updateBacklogItem()` */
  static readonly UpdateBacklogItemPath = '/backlog-items/{backlog-item-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateBacklogItem()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateBacklogItem$Response(params: UpdateBacklogItem$Params, context?: HttpContext): Observable<StrictHttpResponse<BacklogItemResponse>> {
    return updateBacklogItem(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateBacklogItem$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateBacklogItem(params: UpdateBacklogItem$Params, context?: HttpContext): Observable<BacklogItemResponse> {
    return this.updateBacklogItem$Response(params, context).pipe(
      map((r: StrictHttpResponse<BacklogItemResponse>): BacklogItemResponse => r.body)
    );
  }

  /** Path part for operation `deleteBacklogItem()` */
  static readonly DeleteBacklogItemPath = '/backlog-items/{backlog-item-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteBacklogItem()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteBacklogItem$Response(params: DeleteBacklogItem$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return deleteBacklogItem(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteBacklogItem$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteBacklogItem(params: DeleteBacklogItem$Params, context?: HttpContext): Observable<{
}> {
    return this.deleteBacklogItem$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `findAllBacklogItems()` */
  static readonly FindAllBacklogItemsPath = '/backlog-items';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllBacklogItems()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBacklogItems$Response(params?: FindAllBacklogItems$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBacklogItemResponse>> {
    return findAllBacklogItems(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllBacklogItems$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBacklogItems(params?: FindAllBacklogItems$Params, context?: HttpContext): Observable<PageResponseBacklogItemResponse> {
    return this.findAllBacklogItems$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBacklogItemResponse>): PageResponseBacklogItemResponse => r.body)
    );
  }

  /** Path part for operation `createBacklogItem()` */
  static readonly CreateBacklogItemPath = '/backlog-items';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createBacklogItem()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createBacklogItem$Response(params: CreateBacklogItem$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return createBacklogItem(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createBacklogItem$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createBacklogItem(params: CreateBacklogItem$Params, context?: HttpContext): Observable<number> {
    return this.createBacklogItem$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `changeStatut1()` */
  static readonly ChangeStatut1Path = '/backlog-items/{backlog-item-id}/statut';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `changeStatut1()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeStatut1$Response(params: ChangeStatut1$Params, context?: HttpContext): Observable<StrictHttpResponse<BacklogItemResponse>> {
    return changeStatut1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `changeStatut1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeStatut1(params: ChangeStatut1$Params, context?: HttpContext): Observable<BacklogItemResponse> {
    return this.changeStatut1$Response(params, context).pipe(
      map((r: StrictHttpResponse<BacklogItemResponse>): BacklogItemResponse => r.body)
    );
  }

  /** Path part for operation `updatePriorite()` */
  static readonly UpdatePrioritePath = '/backlog-items/{backlog-item-id}/priorite';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updatePriorite()` instead.
   *
   * This method doesn't expect any request body.
   */
  updatePriorite$Response(params: UpdatePriorite$Params, context?: HttpContext): Observable<StrictHttpResponse<BacklogItemResponse>> {
    return updatePriorite(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updatePriorite$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updatePriorite(params: UpdatePriorite$Params, context?: HttpContext): Observable<BacklogItemResponse> {
    return this.updatePriorite$Response(params, context).pipe(
      map((r: StrictHttpResponse<BacklogItemResponse>): BacklogItemResponse => r.body)
    );
  }

  /** Path part for operation `findByStatut()` */
  static readonly FindByStatutPath = '/backlog-items/statut/{statut}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findByStatut()` instead.
   *
   * This method doesn't expect any request body.
   */
  findByStatut$Response(params: FindByStatut$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBacklogItemResponse>> {
    return findByStatut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findByStatut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findByStatut(params: FindByStatut$Params, context?: HttpContext): Observable<PageResponseBacklogItemResponse> {
    return this.findByStatut$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBacklogItemResponse>): PageResponseBacklogItemResponse => r.body)
    );
  }

  /** Path part for operation `searchBacklogItems()` */
  static readonly SearchBacklogItemsPath = '/backlog-items/search';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchBacklogItems()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchBacklogItems$Response(params: SearchBacklogItems$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBacklogItemResponse>> {
    return searchBacklogItems(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchBacklogItems$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchBacklogItems(params: SearchBacklogItems$Params, context?: HttpContext): Observable<PageResponseBacklogItemResponse> {
    return this.searchBacklogItems$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBacklogItemResponse>): PageResponseBacklogItemResponse => r.body)
    );
  }

  /** Path part for operation `findByProductBacklog()` */
  static readonly FindByProductBacklogPath = '/backlog-items/product-backlog/{product-backlog-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findByProductBacklog()` instead.
   *
   * This method doesn't expect any request body.
   */
  findByProductBacklog$Response(params: FindByProductBacklog$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBacklogItemResponse>> {
    return findByProductBacklog(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findByProductBacklog$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findByProductBacklog(params: FindByProductBacklog$Params, context?: HttpContext): Observable<PageResponseBacklogItemResponse> {
    return this.findByProductBacklog$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBacklogItemResponse>): PageResponseBacklogItemResponse => r.body)
    );
  }

  /** Path part for operation `findByPriorityOrder()` */
  static readonly FindByPriorityOrderPath = '/backlog-items/priorite';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findByPriorityOrder()` instead.
   *
   * This method doesn't expect any request body.
   */
  findByPriorityOrder$Response(params: FindByPriorityOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BacklogItemResponse>>> {
    return findByPriorityOrder(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findByPriorityOrder$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findByPriorityOrder(params: FindByPriorityOrder$Params, context?: HttpContext): Observable<Array<BacklogItemResponse>> {
    return this.findByPriorityOrder$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<BacklogItemResponse>>): Array<BacklogItemResponse> => r.body)
    );
  }

  /** Path part for operation `findWithFilters()` */
  static readonly FindWithFiltersPath = '/backlog-items/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findWithFilters()` instead.
   *
   * This method doesn't expect any request body.
   */
  findWithFilters$Response(params?: FindWithFilters$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBacklogItemResponse>> {
    return findWithFilters(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findWithFilters$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findWithFilters(params?: FindWithFilters$Params, context?: HttpContext): Observable<PageResponseBacklogItemResponse> {
    return this.findWithFilters$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBacklogItemResponse>): PageResponseBacklogItemResponse => r.body)
    );
  }

}
