/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addCommentaire } from '../fn/blocage/add-commentaire';
import { AddCommentaire$Params } from '../fn/blocage/add-commentaire';
import { BlocageResponse } from '../models/blocage-response';
import { changeStatut } from '../fn/blocage/change-statut';
import { ChangeStatut$Params } from '../fn/blocage/change-statut';
import { createBlocage } from '../fn/blocage/create-blocage';
import { CreateBlocage$Params } from '../fn/blocage/create-blocage';
import { deleteBlocage } from '../fn/blocage/delete-blocage';
import { DeleteBlocage$Params } from '../fn/blocage/delete-blocage';
import { getAllBlocages } from '../fn/blocage/get-all-blocages';
import { GetAllBlocages$Params } from '../fn/blocage/get-all-blocages';
import { getBlocageById } from '../fn/blocage/get-blocage-by-id';
import { GetBlocageById$Params } from '../fn/blocage/get-blocage-by-id';
import { getBlocagesByStatut } from '../fn/blocage/get-blocages-by-statut';
import { GetBlocagesByStatut$Params } from '../fn/blocage/get-blocages-by-statut';
import { PageResponseBlocageResponse } from '../models/page-response-blocage-response';
import { searchBlocages } from '../fn/blocage/search-blocages';
import { SearchBlocages$Params } from '../fn/blocage/search-blocages';
import { updateBlocage } from '../fn/blocage/update-blocage';
import { UpdateBlocage$Params } from '../fn/blocage/update-blocage';

@Injectable({ providedIn: 'root' })
export class BlocageService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getBlocageById()` */
  static readonly GetBlocageByIdPath = '/blocages/{blocage-id}';

  /**
   * Récupérer un blocage par son ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getBlocageById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBlocageById$Response(params: GetBlocageById$Params, context?: HttpContext): Observable<StrictHttpResponse<BlocageResponse>> {
    return getBlocageById(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer un blocage par son ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getBlocageById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBlocageById(params: GetBlocageById$Params, context?: HttpContext): Observable<BlocageResponse> {
    return this.getBlocageById$Response(params, context).pipe(
      map((r: StrictHttpResponse<BlocageResponse>): BlocageResponse => r.body)
    );
  }

  /** Path part for operation `updateBlocage()` */
  static readonly UpdateBlocagePath = '/blocages/{blocage-id}';

  /**
   * Mettre à jour un blocage.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateBlocage()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateBlocage$Response(params: UpdateBlocage$Params, context?: HttpContext): Observable<StrictHttpResponse<BlocageResponse>> {
    return updateBlocage(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour un blocage.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateBlocage$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateBlocage(params: UpdateBlocage$Params, context?: HttpContext): Observable<BlocageResponse> {
    return this.updateBlocage$Response(params, context).pipe(
      map((r: StrictHttpResponse<BlocageResponse>): BlocageResponse => r.body)
    );
  }

  /** Path part for operation `deleteBlocage()` */
  static readonly DeleteBlocagePath = '/blocages/{blocage-id}';

  /**
   * Supprimer un blocage.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteBlocage()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteBlocage$Response(params: DeleteBlocage$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteBlocage(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprimer un blocage.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteBlocage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteBlocage(params: DeleteBlocage$Params, context?: HttpContext): Observable<void> {
    return this.deleteBlocage$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllBlocages()` */
  static readonly GetAllBlocagesPath = '/blocages';

  /**
   * Récupérer tous les blocages avec pagination.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllBlocages()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllBlocages$Response(params?: GetAllBlocages$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBlocageResponse>> {
    return getAllBlocages(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer tous les blocages avec pagination.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllBlocages$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllBlocages(params?: GetAllBlocages$Params, context?: HttpContext): Observable<PageResponseBlocageResponse> {
    return this.getAllBlocages$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBlocageResponse>): PageResponseBlocageResponse => r.body)
    );
  }

  /** Path part for operation `createBlocage()` */
  static readonly CreateBlocagePath = '/blocages';

  /**
   * Créer un nouveau blocage.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createBlocage()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createBlocage$Response(params: CreateBlocage$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return createBlocage(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer un nouveau blocage.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createBlocage$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createBlocage(params: CreateBlocage$Params, context?: HttpContext): Observable<number> {
    return this.createBlocage$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `addCommentaire()` */
  static readonly AddCommentairePath = '/blocages/{blocage-id}/commentaires';

  /**
   * Ajouter un commentaire à un blocage.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addCommentaire()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addCommentaire$Response(params: AddCommentaire$Params, context?: HttpContext): Observable<StrictHttpResponse<BlocageResponse>> {
    return addCommentaire(this.http, this.rootUrl, params, context);
  }

  /**
   * Ajouter un commentaire à un blocage.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addCommentaire$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addCommentaire(params: AddCommentaire$Params, context?: HttpContext): Observable<BlocageResponse> {
    return this.addCommentaire$Response(params, context).pipe(
      map((r: StrictHttpResponse<BlocageResponse>): BlocageResponse => r.body)
    );
  }

  /** Path part for operation `changeStatut()` */
  static readonly ChangeStatutPath = '/blocages/{blocage-id}/statut';

  /**
   * Changer le statut d'un blocage.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `changeStatut()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeStatut$Response(params: ChangeStatut$Params, context?: HttpContext): Observable<StrictHttpResponse<BlocageResponse>> {
    return changeStatut(this.http, this.rootUrl, params, context);
  }

  /**
   * Changer le statut d'un blocage.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `changeStatut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeStatut(params: ChangeStatut$Params, context?: HttpContext): Observable<BlocageResponse> {
    return this.changeStatut$Response(params, context).pipe(
      map((r: StrictHttpResponse<BlocageResponse>): BlocageResponse => r.body)
    );
  }

  /** Path part for operation `getBlocagesByStatut()` */
  static readonly GetBlocagesByStatutPath = '/blocages/statut/{statut}';

  /**
   * Récupérer les blocages par statut.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getBlocagesByStatut()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBlocagesByStatut$Response(params: GetBlocagesByStatut$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBlocageResponse>> {
    return getBlocagesByStatut(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les blocages par statut.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getBlocagesByStatut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBlocagesByStatut(params: GetBlocagesByStatut$Params, context?: HttpContext): Observable<PageResponseBlocageResponse> {
    return this.getBlocagesByStatut$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBlocageResponse>): PageResponseBlocageResponse => r.body)
    );
  }

  /** Path part for operation `searchBlocages()` */
  static readonly SearchBlocagesPath = '/blocages/search';

  /**
   * Rechercher des blocages avec filtres.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchBlocages()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchBlocages$Response(params?: SearchBlocages$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBlocageResponse>> {
    return searchBlocages(this.http, this.rootUrl, params, context);
  }

  /**
   * Rechercher des blocages avec filtres.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchBlocages$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchBlocages(params?: SearchBlocages$Params, context?: HttpContext): Observable<PageResponseBlocageResponse> {
    return this.searchBlocages$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBlocageResponse>): PageResponseBlocageResponse => r.body)
    );
  }

}
