/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addParticipant } from '../fn/meeting/add-participant';
import { AddParticipant$Params } from '../fn/meeting/add-participant';
import { deleteMeeting } from '../fn/meeting/delete-meeting';
import { DeleteMeeting$Params } from '../fn/meeting/delete-meeting';
import { findAllMeetings } from '../fn/meeting/find-all-meetings';
import { FindAllMeetings$Params } from '../fn/meeting/find-all-meetings';
import { findMeetingById } from '../fn/meeting/find-meeting-by-id';
import { FindMeetingById$Params } from '../fn/meeting/find-meeting-by-id';
import { findMeetingsByProject } from '../fn/meeting/find-meetings-by-project';
import { FindMeetingsByProject$Params } from '../fn/meeting/find-meetings-by-project';
import { findMeetingsByType } from '../fn/meeting/find-meetings-by-type';
import { FindMeetingsByType$Params } from '../fn/meeting/find-meetings-by-type';
import { findMyMeetings } from '../fn/meeting/find-my-meetings';
import { FindMyMeetings$Params } from '../fn/meeting/find-my-meetings';
import { findTodaysMeetings } from '../fn/meeting/find-todays-meetings';
import { FindTodaysMeetings$Params } from '../fn/meeting/find-todays-meetings';
import { findUpcomingMeetings } from '../fn/meeting/find-upcoming-meetings';
import { FindUpcomingMeetings$Params } from '../fn/meeting/find-upcoming-meetings';
import { MeetingResponse } from '../models/meeting-response';
import { PageResponseMeetingResponse } from '../models/page-response-meeting-response';
import { removeParticipant } from '../fn/meeting/remove-participant';
import { RemoveParticipant$Params } from '../fn/meeting/remove-participant';
import { saveMeeting } from '../fn/meeting/save-meeting';
import { SaveMeeting$Params } from '../fn/meeting/save-meeting';
import { updateMeeting } from '../fn/meeting/update-meeting';
import { UpdateMeeting$Params } from '../fn/meeting/update-meeting';

@Injectable({ providedIn: 'root' })
export class MeetingService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findMeetingById()` */
  static readonly FindMeetingByIdPath = '/meetings/{meeting-id}';

  /**
   * Get meeting by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findMeetingById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findMeetingById$Response(params: FindMeetingById$Params, context?: HttpContext): Observable<StrictHttpResponse<MeetingResponse>> {
    return findMeetingById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get meeting by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findMeetingById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findMeetingById(params: FindMeetingById$Params, context?: HttpContext): Observable<MeetingResponse> {
    return this.findMeetingById$Response(params, context).pipe(
      map((r: StrictHttpResponse<MeetingResponse>): MeetingResponse => r.body)
    );
  }

  /** Path part for operation `updateMeeting()` */
  static readonly UpdateMeetingPath = '/meetings/{meeting-id}';

  /**
   * Update a meeting.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateMeeting()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMeeting$Response(params: UpdateMeeting$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return updateMeeting(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a meeting.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateMeeting$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMeeting(params: UpdateMeeting$Params, context?: HttpContext): Observable<number> {
    return this.updateMeeting$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `deleteMeeting()` */
  static readonly DeleteMeetingPath = '/meetings/{meeting-id}';

  /**
   * Delete a meeting.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteMeeting()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteMeeting$Response(params: DeleteMeeting$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteMeeting(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a meeting.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteMeeting$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteMeeting(params: DeleteMeeting$Params, context?: HttpContext): Observable<void> {
    return this.deleteMeeting$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `findAllMeetings()` */
  static readonly FindAllMeetingsPath = '/meetings';

  /**
   * Get all meetings with pagination.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllMeetings()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllMeetings$Response(params?: FindAllMeetings$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseMeetingResponse>> {
    return findAllMeetings(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all meetings with pagination.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllMeetings$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllMeetings(params?: FindAllMeetings$Params, context?: HttpContext): Observable<PageResponseMeetingResponse> {
    return this.findAllMeetings$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseMeetingResponse>): PageResponseMeetingResponse => r.body)
    );
  }

  /** Path part for operation `saveMeeting()` */
  static readonly SaveMeetingPath = '/meetings';

  /**
   * Create a new online meeting.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveMeeting()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveMeeting$Response(params: SaveMeeting$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveMeeting(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new online meeting.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveMeeting$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveMeeting(params: SaveMeeting$Params, context?: HttpContext): Observable<number> {
    return this.saveMeeting$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `addParticipant()` */
  static readonly AddParticipantPath = '/meetings/{meeting-id}/participants/{user-id}';

  /**
   * Add a participant to a meeting.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addParticipant()` instead.
   *
   * This method doesn't expect any request body.
   */
  addParticipant$Response(params: AddParticipant$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return addParticipant(this.http, this.rootUrl, params, context);
  }

  /**
   * Add a participant to a meeting.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addParticipant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  addParticipant(params: AddParticipant$Params, context?: HttpContext): Observable<void> {
    return this.addParticipant$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `removeParticipant()` */
  static readonly RemoveParticipantPath = '/meetings/{meeting-id}/participants/{user-id}';

  /**
   * Remove a participant from a meeting.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeParticipant()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeParticipant$Response(params: RemoveParticipant$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return removeParticipant(this.http, this.rootUrl, params, context);
  }

  /**
   * Remove a participant from a meeting.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeParticipant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeParticipant(params: RemoveParticipant$Params, context?: HttpContext): Observable<void> {
    return this.removeParticipant$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `findUpcomingMeetings()` */
  static readonly FindUpcomingMeetingsPath = '/meetings/upcoming';

  /**
   * Get upcoming meetings.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findUpcomingMeetings()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUpcomingMeetings$Response(params?: FindUpcomingMeetings$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MeetingResponse>>> {
    return findUpcomingMeetings(this.http, this.rootUrl, params, context);
  }

  /**
   * Get upcoming meetings.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findUpcomingMeetings$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUpcomingMeetings(params?: FindUpcomingMeetings$Params, context?: HttpContext): Observable<Array<MeetingResponse>> {
    return this.findUpcomingMeetings$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<MeetingResponse>>): Array<MeetingResponse> => r.body)
    );
  }

  /** Path part for operation `findMeetingsByType()` */
  static readonly FindMeetingsByTypePath = '/meetings/type/{type}';

  /**
   * Get meetings by type.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findMeetingsByType()` instead.
   *
   * This method doesn't expect any request body.
   */
  findMeetingsByType$Response(params: FindMeetingsByType$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseMeetingResponse>> {
    return findMeetingsByType(this.http, this.rootUrl, params, context);
  }

  /**
   * Get meetings by type.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findMeetingsByType$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findMeetingsByType(params: FindMeetingsByType$Params, context?: HttpContext): Observable<PageResponseMeetingResponse> {
    return this.findMeetingsByType$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseMeetingResponse>): PageResponseMeetingResponse => r.body)
    );
  }

  /** Path part for operation `findTodaysMeetings()` */
  static readonly FindTodaysMeetingsPath = '/meetings/today';

  /**
   * Get today's meetings.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findTodaysMeetings()` instead.
   *
   * This method doesn't expect any request body.
   */
  findTodaysMeetings$Response(params?: FindTodaysMeetings$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MeetingResponse>>> {
    return findTodaysMeetings(this.http, this.rootUrl, params, context);
  }

  /**
   * Get today's meetings.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findTodaysMeetings$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findTodaysMeetings(params?: FindTodaysMeetings$Params, context?: HttpContext): Observable<Array<MeetingResponse>> {
    return this.findTodaysMeetings$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<MeetingResponse>>): Array<MeetingResponse> => r.body)
    );
  }

  /** Path part for operation `findMeetingsByProject()` */
  static readonly FindMeetingsByProjectPath = '/meetings/project/{project-id}';

  /**
   * Get meetings by project.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findMeetingsByProject()` instead.
   *
   * This method doesn't expect any request body.
   */
  findMeetingsByProject$Response(params: FindMeetingsByProject$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseMeetingResponse>> {
    return findMeetingsByProject(this.http, this.rootUrl, params, context);
  }

  /**
   * Get meetings by project.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findMeetingsByProject$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findMeetingsByProject(params: FindMeetingsByProject$Params, context?: HttpContext): Observable<PageResponseMeetingResponse> {
    return this.findMeetingsByProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseMeetingResponse>): PageResponseMeetingResponse => r.body)
    );
  }

  /** Path part for operation `findMyMeetings()` */
  static readonly FindMyMeetingsPath = '/meetings/my-meetings';

  /**
   * Get current user's meetings.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findMyMeetings()` instead.
   *
   * This method doesn't expect any request body.
   */
  findMyMeetings$Response(params?: FindMyMeetings$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseMeetingResponse>> {
    return findMyMeetings(this.http, this.rootUrl, params, context);
  }

  /**
   * Get current user's meetings.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findMyMeetings$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findMyMeetings(params?: FindMyMeetings$Params, context?: HttpContext): Observable<PageResponseMeetingResponse> {
    return this.findMyMeetings$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseMeetingResponse>): PageResponseMeetingResponse => r.body)
    );
  }

}
