/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deleteNotification } from '../fn/notification/delete-notification';
import { DeleteNotification$Params } from '../fn/notification/delete-notification';
import { deleteOldNotifications } from '../fn/notification/delete-old-notifications';
import { DeleteOldNotifications$Params } from '../fn/notification/delete-old-notifications';
import { findAllNotifications } from '../fn/notification/find-all-notifications';
import { FindAllNotifications$Params } from '../fn/notification/find-all-notifications';
import { findNotificationById } from '../fn/notification/find-notification-by-id';
import { FindNotificationById$Params } from '../fn/notification/find-notification-by-id';
import { findNotificationsByType } from '../fn/notification/find-notifications-by-type';
import { FindNotificationsByType$Params } from '../fn/notification/find-notifications-by-type';
import { findReadNotifications } from '../fn/notification/find-read-notifications';
import { FindReadNotifications$Params } from '../fn/notification/find-read-notifications';
import { findUnreadNotifications } from '../fn/notification/find-unread-notifications';
import { FindUnreadNotifications$Params } from '../fn/notification/find-unread-notifications';
import { getUnreadCount } from '../fn/notification/get-unread-count';
import { GetUnreadCount$Params } from '../fn/notification/get-unread-count';
import { markAllAsRead } from '../fn/notification/mark-all-as-read';
import { MarkAllAsRead$Params } from '../fn/notification/mark-all-as-read';
import { markAsRead } from '../fn/notification/mark-as-read';
import { MarkAsRead$Params } from '../fn/notification/mark-as-read';
import { markAsUnread } from '../fn/notification/mark-as-unread';
import { MarkAsUnread$Params } from '../fn/notification/mark-as-unread';
import { markMultipleAsRead } from '../fn/notification/mark-multiple-as-read';
import { MarkMultipleAsRead$Params } from '../fn/notification/mark-multiple-as-read';
import { NotificationResponse } from '../models/notification-response';
import { PageResponseNotificationResponse } from '../models/page-response-notification-response';
import { saveNotification } from '../fn/notification/save-notification';
import { SaveNotification$Params } from '../fn/notification/save-notification';
import { searchNotifications } from '../fn/notification/search-notifications';
import { SearchNotifications$Params } from '../fn/notification/search-notifications';
import { updateNotification } from '../fn/notification/update-notification';
import { UpdateNotification$Params } from '../fn/notification/update-notification';

@Injectable({ providedIn: 'root' })
export class NotificationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findNotificationById()` */
  static readonly FindNotificationByIdPath = '/notifications/{notification-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findNotificationById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findNotificationById$Response(params: FindNotificationById$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationResponse>> {
    return findNotificationById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findNotificationById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findNotificationById(params: FindNotificationById$Params, context?: HttpContext): Observable<NotificationResponse> {
    return this.findNotificationById$Response(params, context).pipe(
      map((r: StrictHttpResponse<NotificationResponse>): NotificationResponse => r.body)
    );
  }

  /** Path part for operation `updateNotification()` */
  static readonly UpdateNotificationPath = '/notifications/{notification-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateNotification()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateNotification$Response(params: UpdateNotification$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return updateNotification(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateNotification$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateNotification(params: UpdateNotification$Params, context?: HttpContext): Observable<number> {
    return this.updateNotification$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `deleteNotification()` */
  static readonly DeleteNotificationPath = '/notifications/{notification-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteNotification()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteNotification$Response(params: DeleteNotification$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteNotification(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteNotification$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteNotification(params: DeleteNotification$Params, context?: HttpContext): Observable<void> {
    return this.deleteNotification$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `findAllNotifications()` */
  static readonly FindAllNotificationsPath = '/notifications';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllNotifications()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllNotifications$Response(params?: FindAllNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseNotificationResponse>> {
    return findAllNotifications(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllNotifications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllNotifications(params?: FindAllNotifications$Params, context?: HttpContext): Observable<PageResponseNotificationResponse> {
    return this.findAllNotifications$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseNotificationResponse>): PageResponseNotificationResponse => r.body)
    );
  }

  /** Path part for operation `saveNotification()` */
  static readonly SaveNotificationPath = '/notifications';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveNotification()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveNotification$Response(params: SaveNotification$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveNotification(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveNotification$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveNotification(params: SaveNotification$Params, context?: HttpContext): Observable<number> {
    return this.saveNotification$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `markAsUnread()` */
  static readonly MarkAsUnreadPath = '/notifications/{notification-id}/unread';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `markAsUnread()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAsUnread$Response(params: MarkAsUnread$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return markAsUnread(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `markAsUnread$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAsUnread(params: MarkAsUnread$Params, context?: HttpContext): Observable<void> {
    return this.markAsUnread$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `markAsRead()` */
  static readonly MarkAsReadPath = '/notifications/{notification-id}/read';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `markAsRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAsRead$Response(params: MarkAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return markAsRead(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `markAsRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAsRead(params: MarkAsRead$Params, context?: HttpContext): Observable<void> {
    return this.markAsRead$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `markMultipleAsRead()` */
  static readonly MarkMultipleAsReadPath = '/notifications/mark-multiple-read';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `markMultipleAsRead()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  markMultipleAsRead$Response(params: MarkMultipleAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return markMultipleAsRead(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `markMultipleAsRead$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  markMultipleAsRead(params: MarkMultipleAsRead$Params, context?: HttpContext): Observable<number> {
    return this.markMultipleAsRead$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `markAllAsRead()` */
  static readonly MarkAllAsReadPath = '/notifications/mark-all-read';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `markAllAsRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAllAsRead$Response(params?: MarkAllAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return markAllAsRead(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `markAllAsRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAllAsRead(params?: MarkAllAsRead$Params, context?: HttpContext): Observable<number> {
    return this.markAllAsRead$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findUnreadNotifications()` */
  static readonly FindUnreadNotificationsPath = '/notifications/unread';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findUnreadNotifications()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUnreadNotifications$Response(params?: FindUnreadNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseNotificationResponse>> {
    return findUnreadNotifications(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findUnreadNotifications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUnreadNotifications(params?: FindUnreadNotifications$Params, context?: HttpContext): Observable<PageResponseNotificationResponse> {
    return this.findUnreadNotifications$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseNotificationResponse>): PageResponseNotificationResponse => r.body)
    );
  }

  /** Path part for operation `getUnreadCount()` */
  static readonly GetUnreadCountPath = '/notifications/unread-count';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUnreadCount()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnreadCount$Response(params?: GetUnreadCount$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return getUnreadCount(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUnreadCount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnreadCount(params?: GetUnreadCount$Params, context?: HttpContext): Observable<number> {
    return this.getUnreadCount$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findNotificationsByType()` */
  static readonly FindNotificationsByTypePath = '/notifications/type/{type}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findNotificationsByType()` instead.
   *
   * This method doesn't expect any request body.
   */
  findNotificationsByType$Response(params: FindNotificationsByType$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseNotificationResponse>> {
    return findNotificationsByType(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findNotificationsByType$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findNotificationsByType(params: FindNotificationsByType$Params, context?: HttpContext): Observable<PageResponseNotificationResponse> {
    return this.findNotificationsByType$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseNotificationResponse>): PageResponseNotificationResponse => r.body)
    );
  }

  /** Path part for operation `searchNotifications()` */
  static readonly SearchNotificationsPath = '/notifications/search';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchNotifications()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchNotifications$Response(params?: SearchNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseNotificationResponse>> {
    return searchNotifications(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchNotifications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchNotifications(params?: SearchNotifications$Params, context?: HttpContext): Observable<PageResponseNotificationResponse> {
    return this.searchNotifications$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseNotificationResponse>): PageResponseNotificationResponse => r.body)
    );
  }

  /** Path part for operation `findReadNotifications()` */
  static readonly FindReadNotificationsPath = '/notifications/read';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findReadNotifications()` instead.
   *
   * This method doesn't expect any request body.
   */
  findReadNotifications$Response(params?: FindReadNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseNotificationResponse>> {
    return findReadNotifications(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findReadNotifications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findReadNotifications(params?: FindReadNotifications$Params, context?: HttpContext): Observable<PageResponseNotificationResponse> {
    return this.findReadNotifications$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseNotificationResponse>): PageResponseNotificationResponse => r.body)
    );
  }

  /** Path part for operation `deleteOldNotifications()` */
  static readonly DeleteOldNotificationsPath = '/notifications/cleanup';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteOldNotifications()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteOldNotifications$Response(params?: DeleteOldNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteOldNotifications(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteOldNotifications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteOldNotifications(params?: DeleteOldNotifications$Params, context?: HttpContext): Observable<void> {
    return this.deleteOldNotifications$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
