/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createProductBacklog } from '../fn/product-backlog/create-product-backlog';
import { CreateProductBacklog$Params } from '../fn/product-backlog/create-product-backlog';
import { deleteProductBacklog } from '../fn/product-backlog/delete-product-backlog';
import { DeleteProductBacklog$Params } from '../fn/product-backlog/delete-product-backlog';
import { findAllProductBacklogs } from '../fn/product-backlog/find-all-product-backlogs';
import { FindAllProductBacklogs$Params } from '../fn/product-backlog/find-all-product-backlogs';
import { findProductBacklogById } from '../fn/product-backlog/find-product-backlog-by-id';
import { FindProductBacklogById$Params } from '../fn/product-backlog/find-product-backlog-by-id';
import { findProductBacklogByProjectId } from '../fn/product-backlog/find-product-backlog-by-project-id';
import { FindProductBacklogByProjectId$Params } from '../fn/product-backlog/find-product-backlog-by-project-id';
import { PageResponseProductBacklogResponse } from '../models/page-response-product-backlog-response';
import { ProductBacklogResponse } from '../models/product-backlog-response';
import { updateProductBacklog } from '../fn/product-backlog/update-product-backlog';
import { UpdateProductBacklog$Params } from '../fn/product-backlog/update-product-backlog';

@Injectable({ providedIn: 'root' })
export class ProductBacklogService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findProductBacklogById()` */
  static readonly FindProductBacklogByIdPath = '/product-backlogs/{backlog-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findProductBacklogById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findProductBacklogById$Response(params: FindProductBacklogById$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductBacklogResponse>> {
    return findProductBacklogById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findProductBacklogById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findProductBacklogById(params: FindProductBacklogById$Params, context?: HttpContext): Observable<ProductBacklogResponse> {
    return this.findProductBacklogById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductBacklogResponse>): ProductBacklogResponse => r.body)
    );
  }

  /** Path part for operation `updateProductBacklog()` */
  static readonly UpdateProductBacklogPath = '/product-backlogs/{backlog-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateProductBacklog()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateProductBacklog$Response(params: UpdateProductBacklog$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductBacklogResponse>> {
    return updateProductBacklog(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateProductBacklog$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateProductBacklog(params: UpdateProductBacklog$Params, context?: HttpContext): Observable<ProductBacklogResponse> {
    return this.updateProductBacklog$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductBacklogResponse>): ProductBacklogResponse => r.body)
    );
  }

  /** Path part for operation `deleteProductBacklog()` */
  static readonly DeleteProductBacklogPath = '/product-backlogs/{backlog-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteProductBacklog()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProductBacklog$Response(params: DeleteProductBacklog$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteProductBacklog(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteProductBacklog$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProductBacklog(params: DeleteProductBacklog$Params, context?: HttpContext): Observable<void> {
    return this.deleteProductBacklog$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `findAllProductBacklogs()` */
  static readonly FindAllProductBacklogsPath = '/product-backlogs';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllProductBacklogs()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllProductBacklogs$Response(params?: FindAllProductBacklogs$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseProductBacklogResponse>> {
    return findAllProductBacklogs(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllProductBacklogs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllProductBacklogs(params?: FindAllProductBacklogs$Params, context?: HttpContext): Observable<PageResponseProductBacklogResponse> {
    return this.findAllProductBacklogs$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseProductBacklogResponse>): PageResponseProductBacklogResponse => r.body)
    );
  }

  /** Path part for operation `createProductBacklog()` */
  static readonly CreateProductBacklogPath = '/product-backlogs';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createProductBacklog()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProductBacklog$Response(params: CreateProductBacklog$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return createProductBacklog(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createProductBacklog$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProductBacklog(params: CreateProductBacklog$Params, context?: HttpContext): Observable<number> {
    return this.createProductBacklog$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findProductBacklogByProjectId()` */
  static readonly FindProductBacklogByProjectIdPath = '/product-backlogs/project/{project-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findProductBacklogByProjectId()` instead.
   *
   * This method doesn't expect any request body.
   */
  findProductBacklogByProjectId$Response(params: FindProductBacklogByProjectId$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductBacklogResponse>> {
    return findProductBacklogByProjectId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findProductBacklogByProjectId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findProductBacklogByProjectId(params: FindProductBacklogByProjectId$Params, context?: HttpContext): Observable<ProductBacklogResponse> {
    return this.findProductBacklogByProjectId$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductBacklogResponse>): ProductBacklogResponse => r.body)
    );
  }

}
