/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addUserStoriesToBacklog } from '../fn/sprint-backlog/add-user-stories-to-backlog';
import { AddUserStoriesToBacklog$Params } from '../fn/sprint-backlog/add-user-stories-to-backlog';
import { addUserStoryToBacklog } from '../fn/sprint-backlog/add-user-story-to-backlog';
import { AddUserStoryToBacklog$Params } from '../fn/sprint-backlog/add-user-story-to-backlog';
import { createSprintBacklog } from '../fn/sprint-backlog/create-sprint-backlog';
import { CreateSprintBacklog$Params } from '../fn/sprint-backlog/create-sprint-backlog';
import { deleteSprintBacklog } from '../fn/sprint-backlog/delete-sprint-backlog';
import { DeleteSprintBacklog$Params } from '../fn/sprint-backlog/delete-sprint-backlog';
import { getAllSprintBacklogs } from '../fn/sprint-backlog/get-all-sprint-backlogs';
import { GetAllSprintBacklogs$Params } from '../fn/sprint-backlog/get-all-sprint-backlogs';
import { getSprintBacklogById } from '../fn/sprint-backlog/get-sprint-backlog-by-id';
import { GetSprintBacklogById$Params } from '../fn/sprint-backlog/get-sprint-backlog-by-id';
import { getSprintBacklogBySprintId } from '../fn/sprint-backlog/get-sprint-backlog-by-sprint-id';
import { GetSprintBacklogBySprintId$Params } from '../fn/sprint-backlog/get-sprint-backlog-by-sprint-id';
import { PageResponseSprintBacklogResponse } from '../models/page-response-sprint-backlog-response';
import { removeUserStoryFromBacklog } from '../fn/sprint-backlog/remove-user-story-from-backlog';
import { RemoveUserStoryFromBacklog$Params } from '../fn/sprint-backlog/remove-user-story-from-backlog';
import { SprintBacklogResponse } from '../models/sprint-backlog-response';


/**
 * Sprint Backlog management APIs
 */
@Injectable({ providedIn: 'root' })
export class SprintBacklogService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllSprintBacklogs()` */
  static readonly GetAllSprintBacklogsPath = '/sprint-backlogs';

  /**
   * Get all sprint backlogs with pagination.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllSprintBacklogs()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllSprintBacklogs$Response(params?: GetAllSprintBacklogs$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseSprintBacklogResponse>> {
    return getAllSprintBacklogs(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all sprint backlogs with pagination.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllSprintBacklogs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllSprintBacklogs(params?: GetAllSprintBacklogs$Params, context?: HttpContext): Observable<PageResponseSprintBacklogResponse> {
    return this.getAllSprintBacklogs$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseSprintBacklogResponse>): PageResponseSprintBacklogResponse => r.body)
    );
  }

  /** Path part for operation `createSprintBacklog()` */
  static readonly CreateSprintBacklogPath = '/sprint-backlogs';

  /**
   * Create a new sprint backlog.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createSprintBacklog()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSprintBacklog$Response(params: CreateSprintBacklog$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return createSprintBacklog(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new sprint backlog.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createSprintBacklog$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSprintBacklog(params: CreateSprintBacklog$Params, context?: HttpContext): Observable<number> {
    return this.createSprintBacklog$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `addUserStoriesToBacklog()` */
  static readonly AddUserStoriesToBacklogPath = '/sprint-backlogs/{sprint-backlog-id}/user-stories';

  /**
   * Add multiple user stories to sprint backlog.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addUserStoriesToBacklog()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addUserStoriesToBacklog$Response(params: AddUserStoriesToBacklog$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return addUserStoriesToBacklog(this.http, this.rootUrl, params, context);
  }

  /**
   * Add multiple user stories to sprint backlog.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addUserStoriesToBacklog$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addUserStoriesToBacklog(params: AddUserStoriesToBacklog$Params, context?: HttpContext): Observable<void> {
    return this.addUserStoriesToBacklog$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `addUserStoryToBacklog()` */
  static readonly AddUserStoryToBacklogPath = '/sprint-backlogs/{sprint-backlog-id}/user-stories/{user-story-id}';

  /**
   * Add user story to sprint backlog.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addUserStoryToBacklog()` instead.
   *
   * This method doesn't expect any request body.
   */
  addUserStoryToBacklog$Response(params: AddUserStoryToBacklog$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return addUserStoryToBacklog(this.http, this.rootUrl, params, context);
  }

  /**
   * Add user story to sprint backlog.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addUserStoryToBacklog$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  addUserStoryToBacklog(params: AddUserStoryToBacklog$Params, context?: HttpContext): Observable<void> {
    return this.addUserStoryToBacklog$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `removeUserStoryFromBacklog()` */
  static readonly RemoveUserStoryFromBacklogPath = '/sprint-backlogs/{sprint-backlog-id}/user-stories/{user-story-id}';

  /**
   * Remove user story from sprint backlog.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeUserStoryFromBacklog()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeUserStoryFromBacklog$Response(params: RemoveUserStoryFromBacklog$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return removeUserStoryFromBacklog(this.http, this.rootUrl, params, context);
  }

  /**
   * Remove user story from sprint backlog.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeUserStoryFromBacklog$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeUserStoryFromBacklog(params: RemoveUserStoryFromBacklog$Params, context?: HttpContext): Observable<void> {
    return this.removeUserStoryFromBacklog$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getSprintBacklogById()` */
  static readonly GetSprintBacklogByIdPath = '/sprint-backlogs/{sprint-backlog-id}';

  /**
   * Get sprint backlog by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSprintBacklogById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSprintBacklogById$Response(params: GetSprintBacklogById$Params, context?: HttpContext): Observable<StrictHttpResponse<SprintBacklogResponse>> {
    return getSprintBacklogById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get sprint backlog by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSprintBacklogById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSprintBacklogById(params: GetSprintBacklogById$Params, context?: HttpContext): Observable<SprintBacklogResponse> {
    return this.getSprintBacklogById$Response(params, context).pipe(
      map((r: StrictHttpResponse<SprintBacklogResponse>): SprintBacklogResponse => r.body)
    );
  }

  /** Path part for operation `deleteSprintBacklog()` */
  static readonly DeleteSprintBacklogPath = '/sprint-backlogs/{sprint-backlog-id}';

  /**
   * Delete sprint backlog.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteSprintBacklog()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSprintBacklog$Response(params: DeleteSprintBacklog$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteSprintBacklog(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete sprint backlog.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteSprintBacklog$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSprintBacklog(params: DeleteSprintBacklog$Params, context?: HttpContext): Observable<void> {
    return this.deleteSprintBacklog$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getSprintBacklogBySprintId()` */
  static readonly GetSprintBacklogBySprintIdPath = '/sprint-backlogs/sprint/{sprint-id}';

  /**
   * Get sprint backlog by Sprint ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSprintBacklogBySprintId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSprintBacklogBySprintId$Response(params: GetSprintBacklogBySprintId$Params, context?: HttpContext): Observable<StrictHttpResponse<SprintBacklogResponse>> {
    return getSprintBacklogBySprintId(this.http, this.rootUrl, params, context);
  }

  /**
   * Get sprint backlog by Sprint ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSprintBacklogBySprintId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSprintBacklogBySprintId(params: GetSprintBacklogBySprintId$Params, context?: HttpContext): Observable<SprintBacklogResponse> {
    return this.getSprintBacklogBySprintId$Response(params, context).pipe(
      map((r: StrictHttpResponse<SprintBacklogResponse>): SprintBacklogResponse => r.body)
    );
  }

}
