/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { changeSprintStatut } from '../fn/sprint/change-sprint-statut';
import { ChangeSprintStatut$Params } from '../fn/sprint/change-sprint-statut';
import { deleteSprint } from '../fn/sprint/delete-sprint';
import { DeleteSprint$Params } from '../fn/sprint/delete-sprint';
import { findActiveSprintsOnDate } from '../fn/sprint/find-active-sprints-on-date';
import { FindActiveSprintsOnDate$Params } from '../fn/sprint/find-active-sprints-on-date';
import { findAllSprints } from '../fn/sprint/find-all-sprints';
import { FindAllSprints$Params } from '../fn/sprint/find-all-sprints';
import { findCurrentActiveSprints } from '../fn/sprint/find-current-active-sprints';
import { FindCurrentActiveSprints$Params } from '../fn/sprint/find-current-active-sprints';
import { findSprintById } from '../fn/sprint/find-sprint-by-id';
import { FindSprintById$Params } from '../fn/sprint/find-sprint-by-id';
import { findSprintsByStatut } from '../fn/sprint/find-sprints-by-statut';
import { FindSprintsByStatut$Params } from '../fn/sprint/find-sprints-by-statut';
import { PageResponseSprintResponse } from '../models/page-response-sprint-response';
import { saveSprint } from '../fn/sprint/save-sprint';
import { SaveSprint$Params } from '../fn/sprint/save-sprint';
import { searchSprints } from '../fn/sprint/search-sprints';
import { SearchSprints$Params } from '../fn/sprint/search-sprints';
import { SprintResponse } from '../models/sprint-response';
import { updateSprint } from '../fn/sprint/update-sprint';
import { UpdateSprint$Params } from '../fn/sprint/update-sprint';


/**
 * API de gestion des sprints
 */
@Injectable({ providedIn: 'root' })
export class SprintService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findSprintById()` */
  static readonly FindSprintByIdPath = '/sprints/{sprint-id}';

  /**
   * Récupérer un sprint par son ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findSprintById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findSprintById$Response(params: FindSprintById$Params, context?: HttpContext): Observable<StrictHttpResponse<SprintResponse>> {
    return findSprintById(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer un sprint par son ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findSprintById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findSprintById(params: FindSprintById$Params, context?: HttpContext): Observable<SprintResponse> {
    return this.findSprintById$Response(params, context).pipe(
      map((r: StrictHttpResponse<SprintResponse>): SprintResponse => r.body)
    );
  }

  /** Path part for operation `updateSprint()` */
  static readonly UpdateSprintPath = '/sprints/{sprint-id}';

  /**
   * Mettre à jour un sprint.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateSprint()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSprint$Response(params: UpdateSprint$Params, context?: HttpContext): Observable<StrictHttpResponse<SprintResponse>> {
    return updateSprint(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour un sprint.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateSprint$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSprint(params: UpdateSprint$Params, context?: HttpContext): Observable<SprintResponse> {
    return this.updateSprint$Response(params, context).pipe(
      map((r: StrictHttpResponse<SprintResponse>): SprintResponse => r.body)
    );
  }

  /** Path part for operation `deleteSprint()` */
  static readonly DeleteSprintPath = '/sprints/{sprint-id}';

  /**
   * Supprimer un sprint.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteSprint()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSprint$Response(params: DeleteSprint$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteSprint(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprimer un sprint.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteSprint$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSprint(params: DeleteSprint$Params, context?: HttpContext): Observable<void> {
    return this.deleteSprint$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `findAllSprints()` */
  static readonly FindAllSprintsPath = '/sprints';

  /**
   * Récupérer tous les sprints avec pagination.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllSprints()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllSprints$Response(params?: FindAllSprints$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseSprintResponse>> {
    return findAllSprints(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer tous les sprints avec pagination.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllSprints$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllSprints(params?: FindAllSprints$Params, context?: HttpContext): Observable<PageResponseSprintResponse> {
    return this.findAllSprints$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseSprintResponse>): PageResponseSprintResponse => r.body)
    );
  }

  /** Path part for operation `saveSprint()` */
  static readonly SaveSprintPath = '/sprints';

  /**
   * Créer un nouveau sprint.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveSprint()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveSprint$Response(params: SaveSprint$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveSprint(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer un nouveau sprint.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveSprint$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveSprint(params: SaveSprint$Params, context?: HttpContext): Observable<number> {
    return this.saveSprint$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `changeSprintStatut()` */
  static readonly ChangeSprintStatutPath = '/sprints/{sprint-id}/statut';

  /**
   * Changer le statut d'un sprint.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `changeSprintStatut()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeSprintStatut$Response(params: ChangeSprintStatut$Params, context?: HttpContext): Observable<StrictHttpResponse<SprintResponse>> {
    return changeSprintStatut(this.http, this.rootUrl, params, context);
  }

  /**
   * Changer le statut d'un sprint.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `changeSprintStatut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeSprintStatut(params: ChangeSprintStatut$Params, context?: HttpContext): Observable<SprintResponse> {
    return this.changeSprintStatut$Response(params, context).pipe(
      map((r: StrictHttpResponse<SprintResponse>): SprintResponse => r.body)
    );
  }

  /** Path part for operation `findSprintsByStatut()` */
  static readonly FindSprintsByStatutPath = '/sprints/statut/{statut}';

  /**
   * Récupérer les sprints par statut.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findSprintsByStatut()` instead.
   *
   * This method doesn't expect any request body.
   */
  findSprintsByStatut$Response(params: FindSprintsByStatut$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseSprintResponse>> {
    return findSprintsByStatut(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les sprints par statut.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findSprintsByStatut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findSprintsByStatut(params: FindSprintsByStatut$Params, context?: HttpContext): Observable<PageResponseSprintResponse> {
    return this.findSprintsByStatut$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseSprintResponse>): PageResponseSprintResponse => r.body)
    );
  }

  /** Path part for operation `searchSprints()` */
  static readonly SearchSprintsPath = '/sprints/search';

  /**
   * Rechercher des sprints avec filtres.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchSprints()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchSprints$Response(params?: SearchSprints$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseSprintResponse>> {
    return searchSprints(this.http, this.rootUrl, params, context);
  }

  /**
   * Rechercher des sprints avec filtres.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchSprints$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchSprints(params?: SearchSprints$Params, context?: HttpContext): Observable<PageResponseSprintResponse> {
    return this.searchSprints$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseSprintResponse>): PageResponseSprintResponse => r.body)
    );
  }

  /** Path part for operation `findCurrentActiveSprints()` */
  static readonly FindCurrentActiveSprintsPath = '/sprints/active';

  /**
   * Récupérer les sprints actuellement actifs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findCurrentActiveSprints()` instead.
   *
   * This method doesn't expect any request body.
   */
  findCurrentActiveSprints$Response(params?: FindCurrentActiveSprints$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SprintResponse>>> {
    return findCurrentActiveSprints(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les sprints actuellement actifs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findCurrentActiveSprints$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findCurrentActiveSprints(params?: FindCurrentActiveSprints$Params, context?: HttpContext): Observable<Array<SprintResponse>> {
    return this.findCurrentActiveSprints$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SprintResponse>>): Array<SprintResponse> => r.body)
    );
  }

  /** Path part for operation `findActiveSprintsOnDate()` */
  static readonly FindActiveSprintsOnDatePath = '/sprints/active/{date}';

  /**
   * Récupérer les sprints actifs à une date donnée.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findActiveSprintsOnDate()` instead.
   *
   * This method doesn't expect any request body.
   */
  findActiveSprintsOnDate$Response(params: FindActiveSprintsOnDate$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SprintResponse>>> {
    return findActiveSprintsOnDate(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les sprints actifs à une date donnée.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findActiveSprintsOnDate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findActiveSprintsOnDate(params: FindActiveSprintsOnDate$Params, context?: HttpContext): Observable<Array<SprintResponse>> {
    return this.findActiveSprintsOnDate$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SprintResponse>>): Array<SprintResponse> => r.body)
    );
  }

}
