/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { assignTache } from '../fn/tache/assign-tache';
import { AssignTache$Params } from '../fn/tache/assign-tache';
import { deleteTache } from '../fn/tache/delete-tache';
import { DeleteTache$Params } from '../fn/tache/delete-tache';
import { findAllTaches } from '../fn/tache/find-all-taches';
import { FindAllTaches$Params } from '../fn/tache/find-all-taches';
import { findMyTaches } from '../fn/tache/find-my-taches';
import { FindMyTaches$Params } from '../fn/tache/find-my-taches';
import { findTacheById } from '../fn/tache/find-tache-by-id';
import { FindTacheById$Params } from '../fn/tache/find-tache-by-id';
import { findTachesByStatut } from '../fn/tache/find-taches-by-statut';
import { FindTachesByStatut$Params } from '../fn/tache/find-taches-by-statut';
import { findTachesWithFilters } from '../fn/tache/find-taches-with-filters';
import { FindTachesWithFilters$Params } from '../fn/tache/find-taches-with-filters';
import { PageResponseTacheResponse } from '../models/page-response-tache-response';
import { saveTache } from '../fn/tache/save-tache';
import { SaveTache$Params } from '../fn/tache/save-tache';
import { TacheResponse } from '../models/tache-response';
import { updateTache } from '../fn/tache/update-tache';
import { UpdateTache$Params } from '../fn/tache/update-tache';
import { updateTacheStatut } from '../fn/tache/update-tache-statut';
import { UpdateTacheStatut$Params } from '../fn/tache/update-tache-statut';

@Injectable({ providedIn: 'root' })
export class TacheService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findTacheById()` */
  static readonly FindTacheByIdPath = '/taches/{tache-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findTacheById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findTacheById$Response(params: FindTacheById$Params, context?: HttpContext): Observable<StrictHttpResponse<TacheResponse>> {
    return findTacheById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findTacheById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findTacheById(params: FindTacheById$Params, context?: HttpContext): Observable<TacheResponse> {
    return this.findTacheById$Response(params, context).pipe(
      map((r: StrictHttpResponse<TacheResponse>): TacheResponse => r.body)
    );
  }

  /** Path part for operation `updateTache()` */
  static readonly UpdateTachePath = '/taches/{tache-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTache()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTache$Response(params: UpdateTache$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return updateTache(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTache$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTache(params: UpdateTache$Params, context?: HttpContext): Observable<number> {
    return this.updateTache$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `deleteTache()` */
  static readonly DeleteTachePath = '/taches/{tache-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTache()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTache$Response(params: DeleteTache$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return deleteTache(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTache$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTache(params: DeleteTache$Params, context?: HttpContext): Observable<{
}> {
    return this.deleteTache$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `findAllTaches()` */
  static readonly FindAllTachesPath = '/taches';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllTaches()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllTaches$Response(params?: FindAllTaches$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseTacheResponse>> {
    return findAllTaches(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllTaches$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllTaches(params?: FindAllTaches$Params, context?: HttpContext): Observable<PageResponseTacheResponse> {
    return this.findAllTaches$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseTacheResponse>): PageResponseTacheResponse => r.body)
    );
  }

  /** Path part for operation `saveTache()` */
  static readonly SaveTachePath = '/taches';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveTache()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveTache$Response(params: SaveTache$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveTache(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveTache$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveTache(params: SaveTache$Params, context?: HttpContext): Observable<number> {
    return this.saveTache$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `updateTacheStatut()` */
  static readonly UpdateTacheStatutPath = '/taches/{tache-id}/statut';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTacheStatut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTacheStatut$Response(params: UpdateTacheStatut$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return updateTacheStatut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTacheStatut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTacheStatut(params: UpdateTacheStatut$Params, context?: HttpContext): Observable<number> {
    return this.updateTacheStatut$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `assignTache()` */
  static readonly AssignTachePath = '/taches/{tache-id}/assign';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assignTache()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignTache$Response(params: AssignTache$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return assignTache(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assignTache$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignTache(params: AssignTache$Params, context?: HttpContext): Observable<number> {
    return this.assignTache$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findTachesByStatut()` */
  static readonly FindTachesByStatutPath = '/taches/statut/{statut}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findTachesByStatut()` instead.
   *
   * This method doesn't expect any request body.
   */
  findTachesByStatut$Response(params: FindTachesByStatut$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseTacheResponse>> {
    return findTachesByStatut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findTachesByStatut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findTachesByStatut(params: FindTachesByStatut$Params, context?: HttpContext): Observable<PageResponseTacheResponse> {
    return this.findTachesByStatut$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseTacheResponse>): PageResponseTacheResponse => r.body)
    );
  }

  /** Path part for operation `findTachesWithFilters()` */
  static readonly FindTachesWithFiltersPath = '/taches/search';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findTachesWithFilters()` instead.
   *
   * This method doesn't expect any request body.
   */
  findTachesWithFilters$Response(params?: FindTachesWithFilters$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseTacheResponse>> {
    return findTachesWithFilters(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findTachesWithFilters$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findTachesWithFilters(params?: FindTachesWithFilters$Params, context?: HttpContext): Observable<PageResponseTacheResponse> {
    return this.findTachesWithFilters$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseTacheResponse>): PageResponseTacheResponse => r.body)
    );
  }

  /** Path part for operation `findMyTaches()` */
  static readonly FindMyTachesPath = '/taches/mes-taches';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findMyTaches()` instead.
   *
   * This method doesn't expect any request body.
   */
  findMyTaches$Response(params?: FindMyTaches$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseTacheResponse>> {
    return findMyTaches(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findMyTaches$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findMyTaches(params?: FindMyTaches$Params, context?: HttpContext): Observable<PageResponseTacheResponse> {
    return this.findMyTaches$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseTacheResponse>): PageResponseTacheResponse => r.body)
    );
  }

}
