/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deleteUserStory } from '../fn/user-story/delete-user-story';
import { DeleteUserStory$Params } from '../fn/user-story/delete-user-story';
import { findAllUserStories } from '../fn/user-story/find-all-user-stories';
import { FindAllUserStories$Params } from '../fn/user-story/find-all-user-stories';
import { findAllUserStoriesOrderByPriorite } from '../fn/user-story/find-all-user-stories-order-by-priorite';
import { FindAllUserStoriesOrderByPriorite$Params } from '../fn/user-story/find-all-user-stories-order-by-priorite';
import { findUserStoriesBySprintBacklog } from '../fn/user-story/find-user-stories-by-sprint-backlog';
import { FindUserStoriesBySprintBacklog$Params } from '../fn/user-story/find-user-stories-by-sprint-backlog';
import { findUserStoriesByStatut } from '../fn/user-story/find-user-stories-by-statut';
import { FindUserStoriesByStatut$Params } from '../fn/user-story/find-user-stories-by-statut';
import { findUserStoryById } from '../fn/user-story/find-user-story-by-id';
import { FindUserStoryById$Params } from '../fn/user-story/find-user-story-by-id';
import { PageResponseUserStoryResponse } from '../models/page-response-user-story-response';
import { saveUserStory } from '../fn/user-story/save-user-story';
import { SaveUserStory$Params } from '../fn/user-story/save-user-story';
import { searchUserStories } from '../fn/user-story/search-user-stories';
import { SearchUserStories$Params } from '../fn/user-story/search-user-stories';
import { updateUserStory } from '../fn/user-story/update-user-story';
import { UpdateUserStory$Params } from '../fn/user-story/update-user-story';
import { updateUserStoryStatut } from '../fn/user-story/update-user-story-statut';
import { UpdateUserStoryStatut$Params } from '../fn/user-story/update-user-story-statut';
import { UserStoryResponse } from '../models/user-story-response';

@Injectable({ providedIn: 'root' })
export class UserStoryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findUserStoryById()` */
  static readonly FindUserStoryByIdPath = '/user-stories/{user-story-id}';

  /**
   * Récupérer une User Story par son ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findUserStoryById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUserStoryById$Response(params: FindUserStoryById$Params, context?: HttpContext): Observable<StrictHttpResponse<UserStoryResponse>> {
    return findUserStoryById(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer une User Story par son ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findUserStoryById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUserStoryById(params: FindUserStoryById$Params, context?: HttpContext): Observable<UserStoryResponse> {
    return this.findUserStoryById$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserStoryResponse>): UserStoryResponse => r.body)
    );
  }

  /** Path part for operation `updateUserStory()` */
  static readonly UpdateUserStoryPath = '/user-stories/{user-story-id}';

  /**
   * Mettre à jour une User Story.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateUserStory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUserStory$Response(params: UpdateUserStory$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateUserStory(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour une User Story.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateUserStory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUserStory(params: UpdateUserStory$Params, context?: HttpContext): Observable<void> {
    return this.updateUserStory$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deleteUserStory()` */
  static readonly DeleteUserStoryPath = '/user-stories/{user-story-id}';

  /**
   * Supprimer une User Story.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteUserStory()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteUserStory$Response(params: DeleteUserStory$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteUserStory(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprimer une User Story.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteUserStory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteUserStory(params: DeleteUserStory$Params, context?: HttpContext): Observable<void> {
    return this.deleteUserStory$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `findAllUserStories()` */
  static readonly FindAllUserStoriesPath = '/user-stories';

  /**
   * Récupérer toutes les User Stories avec pagination.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllUserStories()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllUserStories$Response(params?: FindAllUserStories$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseUserStoryResponse>> {
    return findAllUserStories(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer toutes les User Stories avec pagination.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllUserStories$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllUserStories(params?: FindAllUserStories$Params, context?: HttpContext): Observable<PageResponseUserStoryResponse> {
    return this.findAllUserStories$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseUserStoryResponse>): PageResponseUserStoryResponse => r.body)
    );
  }

  /** Path part for operation `saveUserStory()` */
  static readonly SaveUserStoryPath = '/user-stories';

  /**
   * Créer une nouvelle User Story.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveUserStory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveUserStory$Response(params: SaveUserStory$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveUserStory(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer une nouvelle User Story.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveUserStory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveUserStory(params: SaveUserStory$Params, context?: HttpContext): Observable<number> {
    return this.saveUserStory$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `updateUserStoryStatut()` */
  static readonly UpdateUserStoryStatutPath = '/user-stories/{user-story-id}/statut';

  /**
   * Changer le statut d'une User Story.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateUserStoryStatut()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateUserStoryStatut$Response(params: UpdateUserStoryStatut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateUserStoryStatut(this.http, this.rootUrl, params, context);
  }

  /**
   * Changer le statut d'une User Story.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateUserStoryStatut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateUserStoryStatut(params: UpdateUserStoryStatut$Params, context?: HttpContext): Observable<void> {
    return this.updateUserStoryStatut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `findUserStoriesByStatut()` */
  static readonly FindUserStoriesByStatutPath = '/user-stories/statut/{statut}';

  /**
   * Récupérer les User Stories par statut.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findUserStoriesByStatut()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUserStoriesByStatut$Response(params: FindUserStoriesByStatut$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserStoryResponse>>> {
    return findUserStoriesByStatut(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les User Stories par statut.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findUserStoriesByStatut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUserStoriesByStatut(params: FindUserStoriesByStatut$Params, context?: HttpContext): Observable<Array<UserStoryResponse>> {
    return this.findUserStoriesByStatut$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserStoryResponse>>): Array<UserStoryResponse> => r.body)
    );
  }

  /** Path part for operation `findUserStoriesBySprintBacklog()` */
  static readonly FindUserStoriesBySprintBacklogPath = '/user-stories/sprint-backlog/{sprint-backlog-id}';

  /**
   * Récupérer les User Stories d'un Sprint Backlog.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findUserStoriesBySprintBacklog()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUserStoriesBySprintBacklog$Response(params: FindUserStoriesBySprintBacklog$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserStoryResponse>>> {
    return findUserStoriesBySprintBacklog(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les User Stories d'un Sprint Backlog.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findUserStoriesBySprintBacklog$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUserStoriesBySprintBacklog(params: FindUserStoriesBySprintBacklog$Params, context?: HttpContext): Observable<Array<UserStoryResponse>> {
    return this.findUserStoriesBySprintBacklog$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserStoryResponse>>): Array<UserStoryResponse> => r.body)
    );
  }

  /** Path part for operation `searchUserStories()` */
  static readonly SearchUserStoriesPath = '/user-stories/search';

  /**
   * Rechercher des User Stories avec filtres.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchUserStories()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchUserStories$Response(params?: SearchUserStories$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseUserStoryResponse>> {
    return searchUserStories(this.http, this.rootUrl, params, context);
  }

  /**
   * Rechercher des User Stories avec filtres.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchUserStories$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchUserStories(params?: SearchUserStories$Params, context?: HttpContext): Observable<PageResponseUserStoryResponse> {
    return this.searchUserStories$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseUserStoryResponse>): PageResponseUserStoryResponse => r.body)
    );
  }

  /** Path part for operation `findAllUserStoriesOrderByPriorite()` */
  static readonly FindAllUserStoriesOrderByPrioritePath = '/user-stories/priorite';

  /**
   * Récupérer toutes les User Stories triées par priorité.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllUserStoriesOrderByPriorite()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllUserStoriesOrderByPriorite$Response(params?: FindAllUserStoriesOrderByPriorite$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserStoryResponse>>> {
    return findAllUserStoriesOrderByPriorite(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer toutes les User Stories triées par priorité.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllUserStoriesOrderByPriorite$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllUserStoriesOrderByPriorite(params?: FindAllUserStoriesOrderByPriorite$Params, context?: HttpContext): Observable<Array<UserStoryResponse>> {
    return this.findAllUserStoriesOrderByPriorite$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserStoryResponse>>): Array<UserStoryResponse> => r.body)
    );
  }

}
